
# About the project (Week 1)

## Motivation and objectives

I enrolled in the Introduction to Open Data Science to learn the basics of data science and using tools such as R and Git. Also five credits to the Transferable Skills provided some motivation since I need them to complete my studies. I found a link to the course page from an email that specified all the courses compatible with Transferable Skills. 

I don't have that much experience in data science and basically zero experience with R so I'm expecting to learn a lot during the course. However, I'm very experienced in coding so learning R shouldn't be that difficult to me.

## Learning R

Learning R from the book *R for Health Data Science* was very pleasant and easy to follow. The book is very accessible since the reader wasn't expected to know almost any coding. However, for a experienced coder a more condensed tutorial would perhaps have transferred the information more efficiently. Anyhow, I think the book with the complementary exercises are a great way to learn using R.

My favorite topic was *Different types of plots* since it's always nice to create pretty looking plots. The most difficult part was probably *R basics* as this is my first time coding in R. It takes a while to get used to a new language.

## GitHub repository

A link to my GitHub repository: https://github.com/kaapo96/IODS-project


